#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2014-11-24 14:38:29 +0000 (Mon, 24 Nov 2014)
#
#  vim:ts=2:sw=2:et
#
FROM eboraas/apache-php
MAINTAINER <gambol99@gmail.com>
ADD ./hostname.php /var/www/hostname.php
