#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2015-01-15 15:28:59 +0000 (Thu, 15 Jan 2015)
#
#  vim:ts=2:sw=2:et
#
NAME=elasticsearch
AUTHOR=gambol99

.PHONY: build

build:
	docker build -t ${AUTHOR}/${NAME} .

