#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2015-01-19 10:59:24 +0000 (Mon, 19 Jan 2015)
#
#  vim:ts=2:sw=2:et
#
NAME=mesos-config
AUTHOR=gambol99

build:
  docker build -t ${AUTHOR}/${NAME} .

clean:
  docker rmi ${AUTHOR}/${NAME}
